'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
'
Namespace Public_Service
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="_PublicSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ParamOracle()))>  _
    Partial Public Class _Public
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private DWH_Write_LogOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DWH_Update_Log_QueryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DWH_Update_Log_Application_StartOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DWH_Update_Log_Application_EndOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GET_SYS_GUIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DWH_Config_ConnectionStringOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DWH_Config_ApplicationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DWH_Config_Application_Query_SetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DWH_Config_Application_QueryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DWH_Monitor_LogOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectDataToDatatableOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectDataToDatatableTNSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectDataTNSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExecuteDataWithFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExecuteDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Execute_Procedure_OpexOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Datawarehouse_Job_Track.My.MySettings.Default.Datawarehouse_Job_Track_Public_Service__Public
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event DWH_Write_LogCompleted As DWH_Write_LogCompletedEventHandler
        
        '''<remarks/>
        Public Event DWH_Update_Log_QueryCompleted As DWH_Update_Log_QueryCompletedEventHandler
        
        '''<remarks/>
        Public Event DWH_Update_Log_Application_StartCompleted As DWH_Update_Log_Application_StartCompletedEventHandler
        
        '''<remarks/>
        Public Event DWH_Update_Log_Application_EndCompleted As DWH_Update_Log_Application_EndCompletedEventHandler
        
        '''<remarks/>
        Public Event GET_SYS_GUIDCompleted As GET_SYS_GUIDCompletedEventHandler
        
        '''<remarks/>
        Public Event DWH_Config_ConnectionStringCompleted As DWH_Config_ConnectionStringCompletedEventHandler
        
        '''<remarks/>
        Public Event DWH_Config_ApplicationCompleted As DWH_Config_ApplicationCompletedEventHandler
        
        '''<remarks/>
        Public Event DWH_Config_Application_Query_SetCompleted As DWH_Config_Application_Query_SetCompletedEventHandler
        
        '''<remarks/>
        Public Event DWH_Config_Application_QueryCompleted As DWH_Config_Application_QueryCompletedEventHandler
        
        '''<remarks/>
        Public Event DWH_Monitor_LogCompleted As DWH_Monitor_LogCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectDataToDatatableCompleted As SelectDataToDatatableCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectDataToDatatableTNSCompleted As SelectDataToDatatableTNSCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectDataCompleted As SelectDataCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectDataTNSCompleted As SelectDataTNSCompletedEventHandler
        
        '''<remarks/>
        Public Event ExecuteDataWithFileCompleted As ExecuteDataWithFileCompletedEventHandler
        
        '''<remarks/>
        Public Event ExecuteDataCompleted As ExecuteDataCompletedEventHandler
        
        '''<remarks/>
        Public Event Execute_Procedure_OpexCompleted As Execute_Procedure_OpexCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DWH_Write_Log", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DWH_Write_Log(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inUserDB As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String, ByVal inQUERY_SQL_TEXT As String) As String
            Dim results() As Object = Me.Invoke("DWH_Write_Log", New Object() {inLOGIN_GUID, inAPPLICATION_ID, inUserDB, inFRECH_SEQ_ID, inQUERY_ID, inQUERY_SQL_TEXT})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DWH_Write_LogAsync(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inUserDB As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String, ByVal inQUERY_SQL_TEXT As String)
            Me.DWH_Write_LogAsync(inLOGIN_GUID, inAPPLICATION_ID, inUserDB, inFRECH_SEQ_ID, inQUERY_ID, inQUERY_SQL_TEXT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DWH_Write_LogAsync(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inUserDB As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String, ByVal inQUERY_SQL_TEXT As String, ByVal userState As Object)
            If (Me.DWH_Write_LogOperationCompleted Is Nothing) Then
                Me.DWH_Write_LogOperationCompleted = AddressOf Me.OnDWH_Write_LogOperationCompleted
            End If
            Me.InvokeAsync("DWH_Write_Log", New Object() {inLOGIN_GUID, inAPPLICATION_ID, inUserDB, inFRECH_SEQ_ID, inQUERY_ID, inQUERY_SQL_TEXT}, Me.DWH_Write_LogOperationCompleted, userState)
        End Sub
        
        Private Sub OnDWH_Write_LogOperationCompleted(ByVal arg As Object)
            If (Not (Me.DWH_Write_LogCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DWH_Write_LogCompleted(Me, New DWH_Write_LogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DWH_Update_Log_Query", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DWH_Update_Log_Query(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inSEQ_ID As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String, ByVal inRowQTY As Integer) As String
            Dim results() As Object = Me.Invoke("DWH_Update_Log_Query", New Object() {inLOGIN_GUID, inAPPLICATION_ID, inSEQ_ID, inFRECH_SEQ_ID, inQUERY_ID, inRowQTY})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DWH_Update_Log_QueryAsync(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inSEQ_ID As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String, ByVal inRowQTY As Integer)
            Me.DWH_Update_Log_QueryAsync(inLOGIN_GUID, inAPPLICATION_ID, inSEQ_ID, inFRECH_SEQ_ID, inQUERY_ID, inRowQTY, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DWH_Update_Log_QueryAsync(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inSEQ_ID As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String, ByVal inRowQTY As Integer, ByVal userState As Object)
            If (Me.DWH_Update_Log_QueryOperationCompleted Is Nothing) Then
                Me.DWH_Update_Log_QueryOperationCompleted = AddressOf Me.OnDWH_Update_Log_QueryOperationCompleted
            End If
            Me.InvokeAsync("DWH_Update_Log_Query", New Object() {inLOGIN_GUID, inAPPLICATION_ID, inSEQ_ID, inFRECH_SEQ_ID, inQUERY_ID, inRowQTY}, Me.DWH_Update_Log_QueryOperationCompleted, userState)
        End Sub
        
        Private Sub OnDWH_Update_Log_QueryOperationCompleted(ByVal arg As Object)
            If (Not (Me.DWH_Update_Log_QueryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DWH_Update_Log_QueryCompleted(Me, New DWH_Update_Log_QueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DWH_Update_Log_Application_Start", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DWH_Update_Log_Application_Start(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inSEQ_ID As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String) As String
            Dim results() As Object = Me.Invoke("DWH_Update_Log_Application_Start", New Object() {inLOGIN_GUID, inAPPLICATION_ID, inSEQ_ID, inFRECH_SEQ_ID, inQUERY_ID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DWH_Update_Log_Application_StartAsync(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inSEQ_ID As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String)
            Me.DWH_Update_Log_Application_StartAsync(inLOGIN_GUID, inAPPLICATION_ID, inSEQ_ID, inFRECH_SEQ_ID, inQUERY_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DWH_Update_Log_Application_StartAsync(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inSEQ_ID As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String, ByVal userState As Object)
            If (Me.DWH_Update_Log_Application_StartOperationCompleted Is Nothing) Then
                Me.DWH_Update_Log_Application_StartOperationCompleted = AddressOf Me.OnDWH_Update_Log_Application_StartOperationCompleted
            End If
            Me.InvokeAsync("DWH_Update_Log_Application_Start", New Object() {inLOGIN_GUID, inAPPLICATION_ID, inSEQ_ID, inFRECH_SEQ_ID, inQUERY_ID}, Me.DWH_Update_Log_Application_StartOperationCompleted, userState)
        End Sub
        
        Private Sub OnDWH_Update_Log_Application_StartOperationCompleted(ByVal arg As Object)
            If (Not (Me.DWH_Update_Log_Application_StartCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DWH_Update_Log_Application_StartCompleted(Me, New DWH_Update_Log_Application_StartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DWH_Update_Log_Application_End", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DWH_Update_Log_Application_End(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inSEQ_ID As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String) As String
            Dim results() As Object = Me.Invoke("DWH_Update_Log_Application_End", New Object() {inLOGIN_GUID, inAPPLICATION_ID, inSEQ_ID, inFRECH_SEQ_ID, inQUERY_ID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DWH_Update_Log_Application_EndAsync(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inSEQ_ID As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String)
            Me.DWH_Update_Log_Application_EndAsync(inLOGIN_GUID, inAPPLICATION_ID, inSEQ_ID, inFRECH_SEQ_ID, inQUERY_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DWH_Update_Log_Application_EndAsync(ByVal inLOGIN_GUID As String, ByVal inAPPLICATION_ID As String, ByVal inSEQ_ID As String, ByVal inFRECH_SEQ_ID As String, ByVal inQUERY_ID As String, ByVal userState As Object)
            If (Me.DWH_Update_Log_Application_EndOperationCompleted Is Nothing) Then
                Me.DWH_Update_Log_Application_EndOperationCompleted = AddressOf Me.OnDWH_Update_Log_Application_EndOperationCompleted
            End If
            Me.InvokeAsync("DWH_Update_Log_Application_End", New Object() {inLOGIN_GUID, inAPPLICATION_ID, inSEQ_ID, inFRECH_SEQ_ID, inQUERY_ID}, Me.DWH_Update_Log_Application_EndOperationCompleted, userState)
        End Sub
        
        Private Sub OnDWH_Update_Log_Application_EndOperationCompleted(ByVal arg As Object)
            If (Not (Me.DWH_Update_Log_Application_EndCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DWH_Update_Log_Application_EndCompleted(Me, New DWH_Update_Log_Application_EndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_SYS_GUID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GET_SYS_GUID() As String
            Dim results() As Object = Me.Invoke("GET_SYS_GUID", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GET_SYS_GUIDAsync()
            Me.GET_SYS_GUIDAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GET_SYS_GUIDAsync(ByVal userState As Object)
            If (Me.GET_SYS_GUIDOperationCompleted Is Nothing) Then
                Me.GET_SYS_GUIDOperationCompleted = AddressOf Me.OnGET_SYS_GUIDOperationCompleted
            End If
            Me.InvokeAsync("GET_SYS_GUID", New Object(-1) {}, Me.GET_SYS_GUIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGET_SYS_GUIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GET_SYS_GUIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GET_SYS_GUIDCompleted(Me, New GET_SYS_GUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DWH_Config_ConnectionString", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DWH_Config_ConnectionString(ByVal intype As String) As CLS_Config_Connection_String
            Dim results() As Object = Me.Invoke("DWH_Config_ConnectionString", New Object() {intype})
            Return CType(results(0),CLS_Config_Connection_String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DWH_Config_ConnectionStringAsync(ByVal intype As String)
            Me.DWH_Config_ConnectionStringAsync(intype, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DWH_Config_ConnectionStringAsync(ByVal intype As String, ByVal userState As Object)
            If (Me.DWH_Config_ConnectionStringOperationCompleted Is Nothing) Then
                Me.DWH_Config_ConnectionStringOperationCompleted = AddressOf Me.OnDWH_Config_ConnectionStringOperationCompleted
            End If
            Me.InvokeAsync("DWH_Config_ConnectionString", New Object() {intype}, Me.DWH_Config_ConnectionStringOperationCompleted, userState)
        End Sub
        
        Private Sub OnDWH_Config_ConnectionStringOperationCompleted(ByVal arg As Object)
            If (Not (Me.DWH_Config_ConnectionStringCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DWH_Config_ConnectionStringCompleted(Me, New DWH_Config_ConnectionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DWH_Config_Application", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DWH_Config_Application(ByVal inUserName As String, ByVal inComputerName As String, ByVal iniPaddress As String) As Class_User
            Dim results() As Object = Me.Invoke("DWH_Config_Application", New Object() {inUserName, inComputerName, iniPaddress})
            Return CType(results(0),Class_User)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DWH_Config_ApplicationAsync(ByVal inUserName As String, ByVal inComputerName As String, ByVal iniPaddress As String)
            Me.DWH_Config_ApplicationAsync(inUserName, inComputerName, iniPaddress, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DWH_Config_ApplicationAsync(ByVal inUserName As String, ByVal inComputerName As String, ByVal iniPaddress As String, ByVal userState As Object)
            If (Me.DWH_Config_ApplicationOperationCompleted Is Nothing) Then
                Me.DWH_Config_ApplicationOperationCompleted = AddressOf Me.OnDWH_Config_ApplicationOperationCompleted
            End If
            Me.InvokeAsync("DWH_Config_Application", New Object() {inUserName, inComputerName, iniPaddress}, Me.DWH_Config_ApplicationOperationCompleted, userState)
        End Sub
        
        Private Sub OnDWH_Config_ApplicationOperationCompleted(ByVal arg As Object)
            If (Not (Me.DWH_Config_ApplicationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DWH_Config_ApplicationCompleted(Me, New DWH_Config_ApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DWH_Config_Application_Query_Set", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DWH_Config_Application_Query_Set(ByVal sLoginName As String, ByVal iApplicationID As Integer, ByVal sColumnKey As String, ByVal sQueryKey As String) As Boolean
            Dim results() As Object = Me.Invoke("DWH_Config_Application_Query_Set", New Object() {sLoginName, iApplicationID, sColumnKey, sQueryKey})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DWH_Config_Application_Query_SetAsync(ByVal sLoginName As String, ByVal iApplicationID As Integer, ByVal sColumnKey As String, ByVal sQueryKey As String)
            Me.DWH_Config_Application_Query_SetAsync(sLoginName, iApplicationID, sColumnKey, sQueryKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DWH_Config_Application_Query_SetAsync(ByVal sLoginName As String, ByVal iApplicationID As Integer, ByVal sColumnKey As String, ByVal sQueryKey As String, ByVal userState As Object)
            If (Me.DWH_Config_Application_Query_SetOperationCompleted Is Nothing) Then
                Me.DWH_Config_Application_Query_SetOperationCompleted = AddressOf Me.OnDWH_Config_Application_Query_SetOperationCompleted
            End If
            Me.InvokeAsync("DWH_Config_Application_Query_Set", New Object() {sLoginName, iApplicationID, sColumnKey, sQueryKey}, Me.DWH_Config_Application_Query_SetOperationCompleted, userState)
        End Sub
        
        Private Sub OnDWH_Config_Application_Query_SetOperationCompleted(ByVal arg As Object)
            If (Not (Me.DWH_Config_Application_Query_SetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DWH_Config_Application_Query_SetCompleted(Me, New DWH_Config_Application_Query_SetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DWH_Config_Application_Query", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DWH_Config_Application_Query(ByVal iApplicationID As Integer) As CLS_Config_Query()
            Dim results() As Object = Me.Invoke("DWH_Config_Application_Query", New Object() {iApplicationID})
            Return CType(results(0),CLS_Config_Query())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DWH_Config_Application_QueryAsync(ByVal iApplicationID As Integer)
            Me.DWH_Config_Application_QueryAsync(iApplicationID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DWH_Config_Application_QueryAsync(ByVal iApplicationID As Integer, ByVal userState As Object)
            If (Me.DWH_Config_Application_QueryOperationCompleted Is Nothing) Then
                Me.DWH_Config_Application_QueryOperationCompleted = AddressOf Me.OnDWH_Config_Application_QueryOperationCompleted
            End If
            Me.InvokeAsync("DWH_Config_Application_Query", New Object() {iApplicationID}, Me.DWH_Config_Application_QueryOperationCompleted, userState)
        End Sub
        
        Private Sub OnDWH_Config_Application_QueryOperationCompleted(ByVal arg As Object)
            If (Not (Me.DWH_Config_Application_QueryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DWH_Config_Application_QueryCompleted(Me, New DWH_Config_Application_QueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DWH_Monitor_Log", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DWH_Monitor_Log(ByVal inWhere As String) As Class_Monitor_Log()
            Dim results() As Object = Me.Invoke("DWH_Monitor_Log", New Object() {inWhere})
            Return CType(results(0),Class_Monitor_Log())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DWH_Monitor_LogAsync(ByVal inWhere As String)
            Me.DWH_Monitor_LogAsync(inWhere, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DWH_Monitor_LogAsync(ByVal inWhere As String, ByVal userState As Object)
            If (Me.DWH_Monitor_LogOperationCompleted Is Nothing) Then
                Me.DWH_Monitor_LogOperationCompleted = AddressOf Me.OnDWH_Monitor_LogOperationCompleted
            End If
            Me.InvokeAsync("DWH_Monitor_Log", New Object() {inWhere}, Me.DWH_Monitor_LogOperationCompleted, userState)
        End Sub
        
        Private Sub OnDWH_Monitor_LogOperationCompleted(ByVal arg As Object)
            If (Not (Me.DWH_Monitor_LogCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DWH_Monitor_LogCompleted(Me, New DWH_Monitor_LogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectDataToDatatable", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectDataToDatatable(ByVal inConnect As String, ByVal inSQL As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("SelectDataToDatatable", New Object() {inConnect, inSQL})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectDataToDatatableAsync(ByVal inConnect As String, ByVal inSQL As String)
            Me.SelectDataToDatatableAsync(inConnect, inSQL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectDataToDatatableAsync(ByVal inConnect As String, ByVal inSQL As String, ByVal userState As Object)
            If (Me.SelectDataToDatatableOperationCompleted Is Nothing) Then
                Me.SelectDataToDatatableOperationCompleted = AddressOf Me.OnSelectDataToDatatableOperationCompleted
            End If
            Me.InvokeAsync("SelectDataToDatatable", New Object() {inConnect, inSQL}, Me.SelectDataToDatatableOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectDataToDatatableOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectDataToDatatableCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectDataToDatatableCompleted(Me, New SelectDataToDatatableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectDataToDatatableTNS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectDataToDatatableTNS(ByVal inTNSName As String, ByVal inUser As String, ByVal inPassword As String, ByVal inSQL As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("SelectDataToDatatableTNS", New Object() {inTNSName, inUser, inPassword, inSQL})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectDataToDatatableTNSAsync(ByVal inTNSName As String, ByVal inUser As String, ByVal inPassword As String, ByVal inSQL As String)
            Me.SelectDataToDatatableTNSAsync(inTNSName, inUser, inPassword, inSQL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectDataToDatatableTNSAsync(ByVal inTNSName As String, ByVal inUser As String, ByVal inPassword As String, ByVal inSQL As String, ByVal userState As Object)
            If (Me.SelectDataToDatatableTNSOperationCompleted Is Nothing) Then
                Me.SelectDataToDatatableTNSOperationCompleted = AddressOf Me.OnSelectDataToDatatableTNSOperationCompleted
            End If
            Me.InvokeAsync("SelectDataToDatatableTNS", New Object() {inTNSName, inUser, inPassword, inSQL}, Me.SelectDataToDatatableTNSOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectDataToDatatableTNSOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectDataToDatatableTNSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectDataToDatatableTNSCompleted(Me, New SelectDataToDatatableTNSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectData(ByVal inConnect As String, ByVal inSQL As String) As String
            Dim results() As Object = Me.Invoke("SelectData", New Object() {inConnect, inSQL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectDataAsync(ByVal inConnect As String, ByVal inSQL As String)
            Me.SelectDataAsync(inConnect, inSQL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectDataAsync(ByVal inConnect As String, ByVal inSQL As String, ByVal userState As Object)
            If (Me.SelectDataOperationCompleted Is Nothing) Then
                Me.SelectDataOperationCompleted = AddressOf Me.OnSelectDataOperationCompleted
            End If
            Me.InvokeAsync("SelectData", New Object() {inConnect, inSQL}, Me.SelectDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectDataCompleted(Me, New SelectDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectDataTNS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectDataTNS(ByVal inTNSName As String, ByVal inUser As String, ByVal inPassword As String, ByVal inSQL As String) As String
            Dim results() As Object = Me.Invoke("SelectDataTNS", New Object() {inTNSName, inUser, inPassword, inSQL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectDataTNSAsync(ByVal inTNSName As String, ByVal inUser As String, ByVal inPassword As String, ByVal inSQL As String)
            Me.SelectDataTNSAsync(inTNSName, inUser, inPassword, inSQL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectDataTNSAsync(ByVal inTNSName As String, ByVal inUser As String, ByVal inPassword As String, ByVal inSQL As String, ByVal userState As Object)
            If (Me.SelectDataTNSOperationCompleted Is Nothing) Then
                Me.SelectDataTNSOperationCompleted = AddressOf Me.OnSelectDataTNSOperationCompleted
            End If
            Me.InvokeAsync("SelectDataTNS", New Object() {inTNSName, inUser, inPassword, inSQL}, Me.SelectDataTNSOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectDataTNSOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectDataTNSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectDataTNSCompleted(Me, New SelectDataTNSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteDataWithFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExecuteDataWithFile(ByVal inConnect As String, ByVal inSQL As String, ByVal inParam() As ParamOracle) As String
            Dim results() As Object = Me.Invoke("ExecuteDataWithFile", New Object() {inConnect, inSQL, inParam})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExecuteDataWithFileAsync(ByVal inConnect As String, ByVal inSQL As String, ByVal inParam() As ParamOracle)
            Me.ExecuteDataWithFileAsync(inConnect, inSQL, inParam, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExecuteDataWithFileAsync(ByVal inConnect As String, ByVal inSQL As String, ByVal inParam() As ParamOracle, ByVal userState As Object)
            If (Me.ExecuteDataWithFileOperationCompleted Is Nothing) Then
                Me.ExecuteDataWithFileOperationCompleted = AddressOf Me.OnExecuteDataWithFileOperationCompleted
            End If
            Me.InvokeAsync("ExecuteDataWithFile", New Object() {inConnect, inSQL, inParam}, Me.ExecuteDataWithFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnExecuteDataWithFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExecuteDataWithFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExecuteDataWithFileCompleted(Me, New ExecuteDataWithFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExecuteData(ByVal inConnect As String, ByVal inSQL As String) As String
            Dim results() As Object = Me.Invoke("ExecuteData", New Object() {inConnect, inSQL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExecuteDataAsync(ByVal inConnect As String, ByVal inSQL As String)
            Me.ExecuteDataAsync(inConnect, inSQL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExecuteDataAsync(ByVal inConnect As String, ByVal inSQL As String, ByVal userState As Object)
            If (Me.ExecuteDataOperationCompleted Is Nothing) Then
                Me.ExecuteDataOperationCompleted = AddressOf Me.OnExecuteDataOperationCompleted
            End If
            Me.InvokeAsync("ExecuteData", New Object() {inConnect, inSQL}, Me.ExecuteDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnExecuteDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExecuteDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExecuteDataCompleted(Me, New ExecuteDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Execute_Procedure_Opex", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Execute_Procedure_Opex(ByVal inConnect As String, ByVal IN_WEEK As String, ByVal IN_OPEX_CONTROL_SEQ As String) As Object
            Dim results() As Object = Me.Invoke("Execute_Procedure_Opex", New Object() {inConnect, IN_WEEK, IN_OPEX_CONTROL_SEQ})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Execute_Procedure_OpexAsync(ByVal inConnect As String, ByVal IN_WEEK As String, ByVal IN_OPEX_CONTROL_SEQ As String)
            Me.Execute_Procedure_OpexAsync(inConnect, IN_WEEK, IN_OPEX_CONTROL_SEQ, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Execute_Procedure_OpexAsync(ByVal inConnect As String, ByVal IN_WEEK As String, ByVal IN_OPEX_CONTROL_SEQ As String, ByVal userState As Object)
            If (Me.Execute_Procedure_OpexOperationCompleted Is Nothing) Then
                Me.Execute_Procedure_OpexOperationCompleted = AddressOf Me.OnExecute_Procedure_OpexOperationCompleted
            End If
            Me.InvokeAsync("Execute_Procedure_Opex", New Object() {inConnect, IN_WEEK, IN_OPEX_CONTROL_SEQ}, Me.Execute_Procedure_OpexOperationCompleted, userState)
        End Sub
        
        Private Sub OnExecute_Procedure_OpexOperationCompleted(ByVal arg As Object)
            If (Not (Me.Execute_Procedure_OpexCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Execute_Procedure_OpexCompleted(Me, New Execute_Procedure_OpexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CLS_Config_Connection_String
        
        Private connect_IDField As Integer
        
        Private connect_NameField As String
        
        Private connect_TypeField As String
        
        Private connect_StringField As String
        
        Private connect_Find_CharacterField As String
        
        Private connect_Replace_CharacterField As String
        
        '''<remarks/>
        Public Property Connect_ID() As Integer
            Get
                Return Me.connect_IDField
            End Get
            Set
                Me.connect_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Connect_Name() As String
            Get
                Return Me.connect_NameField
            End Get
            Set
                Me.connect_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Connect_Type() As String
            Get
                Return Me.connect_TypeField
            End Get
            Set
                Me.connect_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Connect_String() As String
            Get
                Return Me.connect_StringField
            End Get
            Set
                Me.connect_StringField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Connect_Find_Character() As String
            Get
                Return Me.connect_Find_CharacterField
            End Get
            Set
                Me.connect_Find_CharacterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Connect_Replace_Character() As String
            Get
                Return Me.connect_Replace_CharacterField
            End Get
            Set
                Me.connect_Replace_CharacterField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ParamOracle
        
        Private keyField As String
        
        Private valueField As Object
        
        Private typeField As OracleDbType
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As OracleDbType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum OracleDbType
        
        '''<remarks/>
        BFile
        
        '''<remarks/>
        Blob
        
        '''<remarks/>
        [Byte]
        
        '''<remarks/>
        [Char]
        
        '''<remarks/>
        Clob
        
        '''<remarks/>
        [Date]
        
        '''<remarks/>
        [Decimal]
        
        '''<remarks/>
        [Double]
        
        '''<remarks/>
        [Long]
        
        '''<remarks/>
        LongRaw
        
        '''<remarks/>
        Int16
        
        '''<remarks/>
        Int32
        
        '''<remarks/>
        Int64
        
        '''<remarks/>
        IntervalDS
        
        '''<remarks/>
        IntervalYM
        
        '''<remarks/>
        NClob
        
        '''<remarks/>
        NChar
        
        '''<remarks/>
        NVarchar2
        
        '''<remarks/>
        Raw
        
        '''<remarks/>
        RefCursor
        
        '''<remarks/>
        [Single]
        
        '''<remarks/>
        TimeStamp
        
        '''<remarks/>
        TimeStampLTZ
        
        '''<remarks/>
        TimeStampTZ
        
        '''<remarks/>
        Varchar2
        
        '''<remarks/>
        XmlType
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Class_Monitor_Application_Query
        
        Private sEQ_IDField As Integer
        
        Private qUERY_SQL_TEXTField As String
        
        Private uSER_DBField As String
        
        Private cONNECTION_NAMEField As String
        
        Private rOW_QTYField As Integer
        
        '''<remarks/>
        Public Property SEQ_ID() As Integer
            Get
                Return Me.sEQ_IDField
            End Get
            Set
                Me.sEQ_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QUERY_SQL_TEXT() As String
            Get
                Return Me.qUERY_SQL_TEXTField
            End Get
            Set
                Me.qUERY_SQL_TEXTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property USER_DB() As String
            Get
                Return Me.uSER_DBField
            End Get
            Set
                Me.uSER_DBField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CONNECTION_NAME() As String
            Get
                Return Me.cONNECTION_NAMEField
            End Get
            Set
                Me.cONNECTION_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ROW_QTY() As Integer
            Get
                Return Me.rOW_QTYField
            End Get
            Set
                Me.rOW_QTYField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Class_Monitor_Application
        
        Private list_SQLField() As Class_Monitor_Application_Query
        
        Private application_IDField As String
        
        Private application_NameField As String
        
        Private application_QTYField As Integer
        
        '''<remarks/>
        Public Property List_SQL() As Class_Monitor_Application_Query()
            Get
                Return Me.list_SQLField
            End Get
            Set
                Me.list_SQLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Application_ID() As String
            Get
                Return Me.application_IDField
            End Get
            Set
                Me.application_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Application_Name() As String
            Get
                Return Me.application_NameField
            End Get
            Set
                Me.application_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Application_QTY() As Integer
            Get
                Return Me.application_QTYField
            End Get
            Set
                Me.application_QTYField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Class_Monitor_Log
        
        Private lIST_APPLICATIONField() As Class_Monitor_Application
        
        Private lOGINNAMEField As String
        
        Private cOMPUTERField As String
        
        Private lOGONField As String
        
        Private lOGOFFField As String
        
        Private tYPEField As String
        
        Private gROUPField As String
        
        Private gUIDField As String
        
        '''<remarks/>
        Public Property LIST_APPLICATION() As Class_Monitor_Application()
            Get
                Return Me.lIST_APPLICATIONField
            End Get
            Set
                Me.lIST_APPLICATIONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LOGINNAME() As String
            Get
                Return Me.lOGINNAMEField
            End Get
            Set
                Me.lOGINNAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COMPUTER() As String
            Get
                Return Me.cOMPUTERField
            End Get
            Set
                Me.cOMPUTERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LOGON() As String
            Get
                Return Me.lOGONField
            End Get
            Set
                Me.lOGONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LOGOFF() As String
            Get
                Return Me.lOGOFFField
            End Get
            Set
                Me.lOGOFFField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TYPE() As String
            Get
                Return Me.tYPEField
            End Get
            Set
                Me.tYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GROUP() As String
            Get
                Return Me.gROUPField
            End Get
            Set
                Me.gROUPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GUID() As String
            Get
                Return Me.gUIDField
            End Get
            Set
                Me.gUIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CLS_Config_Query
        
        Private query_IDField As Integer
        
        Private qUery_NameField As String
        
        '''<remarks/>
        Public Property Query_ID() As Integer
            Get
                Return Me.query_IDField
            End Get
            Set
                Me.query_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QUery_Name() As String
            Get
                Return Me.qUery_NameField
            End Get
            Set
                Me.qUery_NameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Class_Application_Column_Parameter
        
        Private parameter_RequiredField As Boolean
        
        Private group_QueryIDField As Integer
        
        Private parameter_IDField As Integer
        
        Private parameter_LabelField As String
        
        Private parameter_FormatField As String
        
        Private parameter_NameField As String
        
        Private parameter_TypeField As String
        
        Private parameter_SizeField As String
        
        Private parameter_ValueField As String
        
        Private parameter_SortField As Decimal
        
        Private parameter_ListField As String
        
        '''<remarks/>
        Public Property Parameter_Required() As Boolean
            Get
                Return Me.parameter_RequiredField
            End Get
            Set
                Me.parameter_RequiredField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Group_QueryID() As Integer
            Get
                Return Me.group_QueryIDField
            End Get
            Set
                Me.group_QueryIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parameter_ID() As Integer
            Get
                Return Me.parameter_IDField
            End Get
            Set
                Me.parameter_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parameter_Label() As String
            Get
                Return Me.parameter_LabelField
            End Get
            Set
                Me.parameter_LabelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parameter_Format() As String
            Get
                Return Me.parameter_FormatField
            End Get
            Set
                Me.parameter_FormatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parameter_Name() As String
            Get
                Return Me.parameter_NameField
            End Get
            Set
                Me.parameter_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parameter_Type() As String
            Get
                Return Me.parameter_TypeField
            End Get
            Set
                Me.parameter_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parameter_Size() As String
            Get
                Return Me.parameter_SizeField
            End Get
            Set
                Me.parameter_SizeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parameter_Value() As String
            Get
                Return Me.parameter_ValueField
            End Get
            Set
                Me.parameter_ValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parameter_Sort() As Decimal
            Get
                Return Me.parameter_SortField
            End Get
            Set
                Me.parameter_SortField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parameter_List() As String
            Get
                Return Me.parameter_ListField
            End Get
            Set
                Me.parameter_ListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Class_Application_Column
        
        Private columnSeqField As Integer
        
        Private columnNameField As String
        
        Private columnIdxField As String
        
        Private columnPositionField As Integer
        
        '''<remarks/>
        Public Property ColumnSeq() As Integer
            Get
                Return Me.columnSeqField
            End Get
            Set
                Me.columnSeqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ColumnName() As String
            Get
                Return Me.columnNameField
            End Get
            Set
                Me.columnNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ColumnIdx() As String
            Get
                Return Me.columnIdxField
            End Get
            Set
                Me.columnIdxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ColumnPosition() As Integer
            Get
                Return Me.columnPositionField
            End Get
            Set
                Me.columnPositionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Class_Application_Group_Query
        
        Private sQL_Query_Group_IDField As Integer
        
        Private sQL_QueryField As String
        
        Private connection_NameField As String
        
        Private connection_StringField As String
        
        Private connection_UserField As String
        
        Private connection_PasswordField As String
        
        Private obj_ColumnField() As Class_Application_Column
        
        Private obj_Column_ParameterField() As Class_Application_Column_Parameter
        
        '''<remarks/>
        Public Property SQL_Query_Group_ID() As Integer
            Get
                Return Me.sQL_Query_Group_IDField
            End Get
            Set
                Me.sQL_Query_Group_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SQL_Query() As String
            Get
                Return Me.sQL_QueryField
            End Get
            Set
                Me.sQL_QueryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Connection_Name() As String
            Get
                Return Me.connection_NameField
            End Get
            Set
                Me.connection_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Connection_String() As String
            Get
                Return Me.connection_StringField
            End Get
            Set
                Me.connection_StringField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Connection_User() As String
            Get
                Return Me.connection_UserField
            End Get
            Set
                Me.connection_UserField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Connection_Password() As String
            Get
                Return Me.connection_PasswordField
            End Get
            Set
                Me.connection_PasswordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Obj_Column() As Class_Application_Column()
            Get
                Return Me.obj_ColumnField
            End Get
            Set
                Me.obj_ColumnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Obj_Column_Parameter() As Class_Application_Column_Parameter()
            Get
                Return Me.obj_Column_ParameterField
            End Get
            Set
                Me.obj_Column_ParameterField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Class_Application
        
        Private application_IDField As Integer
        
        Private return_TypeField As String
        
        Private application_NameField As String
        
        Private application_RemarkField As String
        
        Private read_FrecthField As Integer
        
        Private frecth_TypeField As Integer
        
        Private output_csvField As Integer
        
        Private output_excelField As Integer
        
        Private output_wordField As Integer
        
        Private output_pdfField As Integer
        
        Private output_htmlField As Integer
        
        Private obj_Group_QueryField() As Class_Application_Group_Query
        
        '''<remarks/>
        Public Property Application_ID() As Integer
            Get
                Return Me.application_IDField
            End Get
            Set
                Me.application_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Return_Type() As String
            Get
                Return Me.return_TypeField
            End Get
            Set
                Me.return_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Application_Name() As String
            Get
                Return Me.application_NameField
            End Get
            Set
                Me.application_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Application_Remark() As String
            Get
                Return Me.application_RemarkField
            End Get
            Set
                Me.application_RemarkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Read_Frecth() As Integer
            Get
                Return Me.read_FrecthField
            End Get
            Set
                Me.read_FrecthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Frecth_Type() As Integer
            Get
                Return Me.frecth_TypeField
            End Get
            Set
                Me.frecth_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property output_csv() As Integer
            Get
                Return Me.output_csvField
            End Get
            Set
                Me.output_csvField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property output_excel() As Integer
            Get
                Return Me.output_excelField
            End Get
            Set
                Me.output_excelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property output_word() As Integer
            Get
                Return Me.output_wordField
            End Get
            Set
                Me.output_wordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property output_pdf() As Integer
            Get
                Return Me.output_pdfField
            End Get
            Set
                Me.output_pdfField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property output_html() As Integer
            Get
                Return Me.output_htmlField
            End Get
            Set
                Me.output_htmlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property obj_Group_Query() As Class_Application_Group_Query()
            Get
                Return Me.obj_Group_QueryField
            End Get
            Set
                Me.obj_Group_QueryField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Class_User
        
        Private obj_ApplicationField() As Class_Application
        
        Private type_idField As Integer
        
        Private user_IDField As String
        
        Private user_NameField As String
        
        Private login_NameField As String
        
        Private full_NameField As String
        
        Private emailField As String
        
        Private groupNameField As String
        
        Private computernameField As String
        
        Private ipaddressField As String
        
        '''<remarks/>
        Public Property obj_Application() As Class_Application()
            Get
                Return Me.obj_ApplicationField
            End Get
            Set
                Me.obj_ApplicationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property type_id() As Integer
            Get
                Return Me.type_idField
            End Get
            Set
                Me.type_idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property User_ID() As String
            Get
                Return Me.user_IDField
            End Get
            Set
                Me.user_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property User_Name() As String
            Get
                Return Me.user_NameField
            End Get
            Set
                Me.user_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Login_Name() As String
            Get
                Return Me.login_NameField
            End Get
            Set
                Me.login_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Full_Name() As String
            Get
                Return Me.full_NameField
            End Get
            Set
                Me.full_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GroupName() As String
            Get
                Return Me.groupNameField
            End Get
            Set
                Me.groupNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Computername() As String
            Get
                Return Me.computernameField
            End Get
            Set
                Me.computernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ipaddress() As String
            Get
                Return Me.ipaddressField
            End Get
            Set
                Me.ipaddressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DWH_Write_LogCompletedEventHandler(ByVal sender As Object, ByVal e As DWH_Write_LogCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DWH_Write_LogCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DWH_Update_Log_QueryCompletedEventHandler(ByVal sender As Object, ByVal e As DWH_Update_Log_QueryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DWH_Update_Log_QueryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DWH_Update_Log_Application_StartCompletedEventHandler(ByVal sender As Object, ByVal e As DWH_Update_Log_Application_StartCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DWH_Update_Log_Application_StartCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DWH_Update_Log_Application_EndCompletedEventHandler(ByVal sender As Object, ByVal e As DWH_Update_Log_Application_EndCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DWH_Update_Log_Application_EndCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GET_SYS_GUIDCompletedEventHandler(ByVal sender As Object, ByVal e As GET_SYS_GUIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GET_SYS_GUIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DWH_Config_ConnectionStringCompletedEventHandler(ByVal sender As Object, ByVal e As DWH_Config_ConnectionStringCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DWH_Config_ConnectionStringCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CLS_Config_Connection_String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CLS_Config_Connection_String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DWH_Config_ApplicationCompletedEventHandler(ByVal sender As Object, ByVal e As DWH_Config_ApplicationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DWH_Config_ApplicationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Class_User
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Class_User)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DWH_Config_Application_Query_SetCompletedEventHandler(ByVal sender As Object, ByVal e As DWH_Config_Application_Query_SetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DWH_Config_Application_Query_SetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DWH_Config_Application_QueryCompletedEventHandler(ByVal sender As Object, ByVal e As DWH_Config_Application_QueryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DWH_Config_Application_QueryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CLS_Config_Query()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CLS_Config_Query())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DWH_Monitor_LogCompletedEventHandler(ByVal sender As Object, ByVal e As DWH_Monitor_LogCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DWH_Monitor_LogCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Class_Monitor_Log()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Class_Monitor_Log())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectDataToDatatableCompletedEventHandler(ByVal sender As Object, ByVal e As SelectDataToDatatableCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectDataToDatatableCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectDataToDatatableTNSCompletedEventHandler(ByVal sender As Object, ByVal e As SelectDataToDatatableTNSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectDataToDatatableTNSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectDataCompletedEventHandler(ByVal sender As Object, ByVal e As SelectDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectDataTNSCompletedEventHandler(ByVal sender As Object, ByVal e As SelectDataTNSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectDataTNSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ExecuteDataWithFileCompletedEventHandler(ByVal sender As Object, ByVal e As ExecuteDataWithFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExecuteDataWithFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ExecuteDataCompletedEventHandler(ByVal sender As Object, ByVal e As ExecuteDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExecuteDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub Execute_Procedure_OpexCompletedEventHandler(ByVal sender As Object, ByVal e As Execute_Procedure_OpexCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Execute_Procedure_OpexCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
End Namespace
